project:
  type: website

website:
  title: "Ander Díaz-Navarro"
  favicon: img/favicon_adn.png
  google-analytics: "G-VWCMSVB59E"

format:
  html:
    theme:
      - cosmo
      - brand
    css: [styles.css,
          https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css,
          https://cdn.rawgit.com/jpswalsh/academicons/master/css/academicons.min.css]
    include-in-header:
        - file: "scripts_js.html"
    page-layout: full



